apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'expo.modules.ibeaconscanner'
version = '1.0.0'

def expoModulesCorePlugin = new File(project(':expo-modules-core').projectDir.absolutePath, 'ExpoModulesCorePlugin.gradle')
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()

android {
  namespace 'expo.modules.ibeaconscanner'
  compileSdk safeExtGet('compileSdkVersion', 35)
  defaultConfig {
    minSdk safeExtGet('minSdkVersion', 24)
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }
  kotlinOptions {
    jvmTarget = '17'
  }
}

repositories {
  mavenCentral()
}

dependencies {
  implementation project(':expo-modules-core')
}
